core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vacancies.urls.urls'))
]

core/vacancies/urls/urls.py
from django.urls import path, include

from vacancies.views.default.vacancy.create import VacancyCreateView
from vacancies.views.default.vacancy.list import VacancyListV1View

vacancies_patterns = [
    path("", VacancyListV1View.as_view(), name="vacancies-list"),
    path("create/", VacancyCreateView.as_view(), name="vacancies-create"),
]

urlpatterns = [
    path("", include(vacancies_patterns)),
]

core/vacancies/models.py
from django.db import models


class Language(models.TextChoices):
    PYTHON = "python", "Python"
    PHP = "php", "PHP"
    JAVASCRIPT = "javascript", "JavaScript"
    C_PP = "cpp", "C++"
    C_SHARP = "csharp", "C#"
    JAVA = "java", "Java"
    GOLANG = "golang", "Go"
    RUST = "rust", "Rust"
    RUBY = "ruby", "Ruby"
    SQL = "sql", "SQL"


class Speciality(models.TextChoices):
    DEVOPS = "devops", "DevOps-инженер"
    ANALYTICS = "analytics", "Аналитик"
    DATA_SCIENTIST = "data-scientist", "Дата-сайентист"
    MENTOR = "mentor", "Преподаватель"
    DEVELOPER = "developer", "Программист"
    LEAD = "lead", "Руководитель группы разработки"
    SYSTEM_ADMINISTRATOR = "sysadmin", "Системный администратор"
    QA = "qa", "Тестировщик"


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class StackTool(BaseModel):
    name = models.CharField(max_length=255, verbose_name="Ключевые навыки", unique=True)

    class Meta:
        verbose_name = "Стек"
        ordering = ("name",)

    def __str__(self):
        return self.name


class City(BaseModel):
    name = models.CharField(max_length=32, verbose_name="Название", unique=True)

    class Meta:
        verbose_name = "Город"
        verbose_name_plural = "Города"
        ordering = ("name",)

    def __str__(self):
        return self.name


class Company(BaseModel):
    city = models.ForeignKey(
        "vacancies.City",
        verbose_name="Город",
        on_delete=models.DO_NOTHING,
        related_name="companies",
        blank=True,
        null=True,
    )
    name = models.CharField(max_length=255, verbose_name="Название")
    description = models.TextField(verbose_name="Описание", blank=True, null=True)

    class Meta:
        verbose_name = "Компания"
        verbose_name_plural = "Компании"
        ordering = ("name",)
        unique_together = ("city", "name")

    def __str__(self):
        return self.name


class Vacancy(BaseModel):
    class Experience(models.TextChoices):
        NO_EXPERIENCE = "no_experience", "без опыта"
        BETWEEN_1_3 = "between_1_2", "от 1 до 3 лет"
        BETWEEN_3_5 = "between_3_5", "от 3 до 5 лет"
        MORE_THAN_5 = "more_than_5", "Более 5 лет"

    class Grade(models.TextChoices):
        TRAINEE = "trainee", "Стажер"
        JUNIOR = "junior", "Джуниор"
        MIDDLE = "middle", "Миддл"
        SENIOR = "senior", "Сеньор"
        LEAD = "lead", "Лид"

    company = models.ForeignKey(
        "vacancies.Company",
        verbose_name="Компания",
        on_delete=models.CASCADE,
        related_name="vacancies",
    )
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    text = models.TextField(verbose_name="Описание", blank=True, null=True)
    speciality = models.CharField(
        max_length=255,
        verbose_name="Специализация",
        choices=Speciality.choices,
    )
    language = models.CharField(
        max_length=255,
        verbose_name="Язык программирования",
        choices=Language.choices,
    )
    experience = models.CharField(
        max_length=255,
        verbose_name="Опыт",
        choices=Experience.choices,
    )
    grade = models.CharField(
        max_length=255,
        verbose_name="Грейд",
        choices=Grade.choices,
        blank=True,
        null=True,
    )
    is_remote = models.BooleanField(
        default=False,
        verbose_name="Можно работать удаленно",
    )
    salary_from = models.FloatField(null=True, blank=True, verbose_name="Зарплата от")
    salary_to = models.FloatField(null=True, blank=True, verbose_name="Зарплата до")
    stack = models.ManyToManyField(
        "vacancies.StackTool",
        related_name="vacancies",
        verbose_name="Стек",
        blank=True,
    )
    link = models.URLField(null=True, blank=True, verbose_name="Ссылка на вакансию")

    class Meta:
        verbose_name = "Вакансия"
        verbose_name_plural = "Вакансии"
        ordering = ("salary_from", "salary_to")
        unique_together = ("title", "company", "text", "speciality", "language", )

    def __str__(self):
        return self.title


class Resume(BaseModel):
    employee = models.ForeignKey(
        "users.Employee",
        on_delete=models.CASCADE,
        related_name="resumes",
        verbose_name="Работник",
    )
    position = models.CharField(max_length=255, verbose_name="Желаемая должность")
    speciality = models.CharField(
        max_length=255,
        verbose_name="Специальность",
        choices=Speciality.choices,
    )
    language = models.CharField(
        max_length=255,
        verbose_name="Основной язык программирования",
        choices=Language.choices,
    )
    stack = models.ManyToManyField(
        "vacancies.StackTool",
        related_name="resumes",
        verbose_name="Стек",
    )

    class Meta:
        verbose_name = "Резюме"
        verbose_name_plural = "Резюме"
        unique_together = ("employee", "position", "speciality")

    def __str__(self):
        return self.position

    @property
    def get_experience(self):
        # TODO добавить функционал
        return self.position


class JobPlace(BaseModel):
    company = models.ForeignKey(
        "vacancies.Company",
        on_delete=models.DO_NOTHING,
        related_name="job_places",
        verbose_name="Компания",
    )
    resume = models.ForeignKey(
        "vacancies.Resume",
        on_delete=models.CASCADE,
        related_name="job_places",
        verbose_name="Резюме",
    )
    position = models.CharField(max_length=255, verbose_name="Должность")
    speciality = models.CharField(
        max_length=255,
        verbose_name="Специальность",
        choices=Speciality.choices,
    )
    job_start = models.DateField(verbose_name="Дата приема")
    job_end = models.DateField(verbose_name="Дата увольнения", null=True, blank=True)
    description = models.TextField(verbose_name="Описание", blank=True, null=True)

    class Meta:
        verbose_name = "Место работы"
        verbose_name_plural = "Места работы"

    def __str__(self):
        return self.position

core/vacancies/forms.py
from betterforms.forms import BetterModelForm
from betterforms.multiform import MultiModelForm
from django import forms
from django.db import IntegrityError
from django.forms import BooleanField

from users.models import Employer
from vacancies.models import Vacancy, StackTool, Company


class BaseModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if not isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-control  mb-4"


class StackForm(BaseModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "sql,html,power bi"}),
        label="Ключевые навыки (через запятую):",
        required=False,
    )

    class Meta:
        model = StackTool
        exclude = ['created_at', ]


class VacancyForm(BaseModelForm):
    class Meta:
        model = Vacancy
        exclude = (
            "company",
            "stack",
            "grade",
            "created_at",
            "link",
        )


class CreateVacancyMultiForm(MultiModelForm):
    form_classes = {
        'vacancy': VacancyForm,
        'stack': StackForm,
    }

    def save(self, commit=True):
        objects = super(CreateVacancyMultiForm, self).save(commit=False)

        if commit:
            stack_name_list = objects["stack"].name.split(",") if objects[
                "stack"].name else []
            stack_obj_list = []
            for stack in stack_name_list:
                obj, _ = StackTool.objects.get_or_create(
                    name=stack.strip().replace(" ", "_").lower(),
                )
                stack_obj_list.append(obj)
            employer = Employer.objects.filter(user_id=self.data["user_id"]).first()
            if not employer:
                return objects
            vacancy = objects["vacancy"]
            vacancy.company = employer.company
            try:
                vacancy.save()
                vacancy.stack.set(stack_obj_list)
            except IntegrityError:
                return objects

        return objects

core/vacancies/templates/vacancy/create.html
{% extends "base.html" %}
{% block content %}
    
    <form class="mb-4 p-4" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-success" type="submit">Сохранить</button>
    </form>
    <style>
        #id_vacancy-is_remote {
            display: block;
            margin-bottom: 1.5rem;
        }
    </style>
{% endblock %}

core/vacancies/templates/vacancy/list.html
{% extends "base.html" %}
{% block content %}
    {% include "vacancy/partial.html" %}
{% endblock %}

core/vacancies/templates/vacancy/partial.html
<div id="vacancies-list">
    Найдено вакансий: {{ count }}
    <hr>
    {% for object in object_list %}
        <div class="vacancy-card mb-4 p-2">
            <div class="vacancy-card-title mb-2">
                {{ object.title }}
                <span class="vacancy-title-text">
                    {{ object.get_experience_display }}
                </span>
                {% if object.is_remote %}
                    <span class="vacancy-title-text"> Удаленка</span>
                {% endif %}
            </div>
            {% if object.salary_from and object.salary_to %}
                <div class="vacancy-card-salary mb-2">
                    от: &nbsp;<span
                        class="salary">{{ object.salary_from|format_salary }}</span>
                    &nbsp;до: &nbsp;<span
                        class="salary">{{ object.salary_to|format_salary }}</span>
                </div>
            {% elif object.salary_from %}
                <div class="vacancy-card-salary mb-2">
                    от: <span
                        class="salary">{{ object.salary_from|format_salary }}</span>
                </div>
            {% else %}
                <div class="vacancy-card-salary mb-2">
                    до: <span
                        class="salary">{{ object.salary_to|format_salary }}</span>
                </div>
            {% endif %}
            {% if object.stack %}
                <div class="vacancy-card-stack mb-2">
                    {% for stack in object.stack.all %}
                        <span class="vacancy-card-stack-item">
                        {{ stack }}
                    </span>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="vacancy-card-city mb-2">
                <i class="fa fa-map-marker" aria-hidden="true"></i>&nbsp;
                {{ object.company.city.name }}
            </div>
            <div class="vacancy-card-company mb-2">
                <i class="fa fa-building" aria-hidden="true"></i>
                {{ object.company.name }}
            </div>
        </div>
    {% endfor %}
</div>